# Generated by Django 4.2.27 on 2026-01-31 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("fati_indicators", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metric_name",
                    models.CharField(max_length=100, verbose_name="nom de la métrique"),
                ),
                ("metric_value", models.FloatField(verbose_name="valeur")),
                (
                    "dimension_1",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="dimension 1"
                    ),
                ),
                (
                    "dimension_2",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="dimension 2"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="horodatage"
                    ),
                ),
            ],
            options={
                "verbose_name": "métrique système",
                "verbose_name_plural": "métriques système",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["metric_name", "-timestamp"],
                        name="fati_audit__metric__041fc0_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DataQualityCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "check_type",
                    models.CharField(
                        choices=[
                            ("completeness", "Complétude"),
                            ("consistency", "Cohérence"),
                            ("validity", "Validité"),
                            ("timeliness", "Ponctualité"),
                        ],
                        max_length=20,
                        verbose_name="type de vérification",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("passed", "Réussi"),
                            ("warning", "Avertissement"),
                            ("failed", "Échec"),
                        ],
                        max_length=20,
                        verbose_name="statut",
                    ),
                ),
                ("message", models.TextField(blank=True, verbose_name="message")),
                (
                    "details",
                    models.JSONField(blank=True, default=dict, verbose_name="détails"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "indicator_value",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quality_checks",
                        to="fati_indicators.indicatorvalue",
                        verbose_name="valeur d'indicateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "vérification de qualité",
                "verbose_name_plural": "vérifications de qualité",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_name",
                    models.CharField(max_length=255, verbose_name="nom utilisateur"),
                ),
                (
                    "user_role",
                    models.CharField(max_length=50, verbose_name="rôle utilisateur"),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Créer"),
                            ("update", "Modifier"),
                            ("delete", "Supprimer"),
                            ("validate", "Valider"),
                            ("reject", "Rejeter"),
                            ("export", "Exporter"),
                            ("login", "Connexion"),
                            ("logout", "Déconnexion"),
                            ("view", "Consultation"),
                        ],
                        max_length=20,
                        verbose_name="action",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(max_length=100, verbose_name="type d'entité"),
                ),
                (
                    "entity_id",
                    models.CharField(max_length=100, verbose_name="ID de l'entité"),
                ),
                (
                    "entity_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="nom de l'entité"
                    ),
                ),
                (
                    "old_values",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="anciennes valeurs"
                    ),
                ),
                (
                    "new_values",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="nouvelles valeurs"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="adresse IP"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="user agent")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "journal d'audit",
                "verbose_name_plural": "journaux d'audit",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="fati_audit__user_id_6e72cc_idx",
                    ),
                    models.Index(
                        fields=["entity_type", "entity_id"],
                        name="fati_audit__entity__2e8918_idx",
                    ),
                    models.Index(
                        fields=["action", "-created_at"],
                        name="fati_audit__action_ea7055_idx",
                    ),
                ],
            },
        ),
    ]
