# Generated by Django 4.2.27 on 2026-01-31 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fati_geography", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Administrateur"),
                            ("institution", "Institution"),
                            ("sector_health", "Secteur Santé"),
                            ("sector_education", "Secteur Éducation"),
                            ("local_manager", "Responsable Local"),
                            ("contributor", "Contributeur"),
                            ("viewer", "Lecteur"),
                        ],
                        max_length=20,
                        verbose_name="rôle",
                    ),
                ),
                (
                    "resource",
                    models.CharField(
                        choices=[
                            ("dashboard", "Tableau de bord"),
                            ("indicators", "Indicateurs"),
                            ("facilities", "Structures"),
                            ("collections", "Collectes"),
                            ("reports", "Rapports"),
                            ("users", "Utilisateurs"),
                            ("settings", "Paramètres"),
                            ("audit", "Audit"),
                            ("*", "Tout"),
                        ],
                        max_length=50,
                        verbose_name="ressource",
                    ),
                ),
                ("actions", models.JSONField(default=list, verbose_name="actions")),
            ],
            options={
                "verbose_name": "permission",
                "verbose_name_plural": "permissions",
                "unique_together": {("role", "resource")},
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email"
                    ),
                ),
                ("first_name", models.CharField(max_length=150, verbose_name="prénom")),
                ("last_name", models.CharField(max_length=150, verbose_name="nom")),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Administrateur"),
                            ("institution", "Institution"),
                            ("sector_health", "Secteur Santé"),
                            ("sector_education", "Secteur Éducation"),
                            ("local_manager", "Responsable Local"),
                            ("contributor", "Contributeur"),
                            ("viewer", "Lecteur"),
                        ],
                        default="viewer",
                        max_length=20,
                        verbose_name="rôle",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Actif"),
                            ("inactive", "Inactif"),
                            ("pending", "En attente"),
                            ("suspended", "Suspendu"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="statut",
                    ),
                ),
                (
                    "organization",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="organisation"
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="département"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="téléphone"
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="avatars/",
                        verbose_name="avatar",
                    ),
                ),
                (
                    "last_login_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="dernière connexion"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="modifié le"),
                ),
                (
                    "is_staff",
                    models.BooleanField(default=False, verbose_name="staff status"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="actif")),
                (
                    "is_superuser",
                    models.BooleanField(default=False, verbose_name="superutilisateur"),
                ),
                (
                    "assigned_commune",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_users",
                        to="fati_geography.commune",
                        verbose_name="commune assignée",
                    ),
                ),
                (
                    "assigned_department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_users",
                        to="fati_geography.department",
                        verbose_name="département assigné",
                    ),
                ),
                (
                    "assigned_region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_users",
                        to="fati_geography.region",
                        verbose_name="région assignée",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "utilisateur",
                "verbose_name_plural": "utilisateurs",
                "ordering": ["-created_at"],
            },
        ),
    ]
