# Generated by Django 4.2.27 on 2026-02-08 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fati_accounts", "0002_remove_sector_roles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permission",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Administrateur"),
                    ("institution", "Décideur"),
                    ("local_manager", "Agent de saisie"),
                    ("annonceur", "Public"),
                    ("viewer", "Lecteur"),
                ],
                max_length=20,
                verbose_name="rôle",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Administrateur"),
                    ("institution", "Décideur"),
                    ("local_manager", "Agent de saisie"),
                    ("annonceur", "Public"),
                    ("viewer", "Lecteur"),
                ],
                default="viewer",
                max_length=20,
                verbose_name="rôle",
            ),
        ),
    ]
