# Generated by Django 4.2.27 on 2026-01-31 14:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("fati_geography", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Indicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="code"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="nom")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "sector",
                    models.CharField(
                        choices=[("health", "Santé"), ("education", "Éducation")],
                        max_length=20,
                        verbose_name="secteur",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("access", "Accès"),
                            ("quality", "Qualité"),
                            ("resources", "Ressources"),
                            ("outcomes", "Résultats"),
                            ("infrastructure", "Infrastructure"),
                            ("personnel", "Personnel"),
                            ("finance", "Finance"),
                        ],
                        max_length=20,
                        verbose_name="catégorie",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("number", "Nombre"),
                            ("percentage", "Pourcentage"),
                            ("ratio", "Ratio"),
                            ("currency", "Monnaie"),
                            ("count", "Comptage"),
                        ],
                        default="number",
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                (
                    "unit",
                    models.CharField(blank=True, max_length=50, verbose_name="unité"),
                ),
                ("formula", models.TextField(blank=True, verbose_name="formule")),
                (
                    "denominator",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="dénominateur"
                    ),
                ),
                (
                    "target_value",
                    models.FloatField(
                        blank=True, null=True, verbose_name="valeur cible"
                    ),
                ),
                (
                    "alert_threshold",
                    models.FloatField(
                        blank=True, null=True, verbose_name="seuil d'alerte"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="actif")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="ordre")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="modifié le"),
                ),
            ],
            options={
                "verbose_name": "indicateur",
                "verbose_name_plural": "indicateurs",
                "ordering": ["sector", "category", "order", "name"],
            },
        ),
        migrations.CreateModel(
            name="IndicatorValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField(verbose_name="année")),
                (
                    "period",
                    models.CharField(blank=True, max_length=20, verbose_name="période"),
                ),
                ("value", models.FloatField(verbose_name="valeur")),
                (
                    "previous_value",
                    models.FloatField(
                        blank=True, null=True, verbose_name="valeur précédente"
                    ),
                ),
                (
                    "target_value",
                    models.FloatField(
                        blank=True, null=True, verbose_name="valeur cible"
                    ),
                ),
                (
                    "variation",
                    models.FloatField(
                        blank=True, null=True, verbose_name="variation (%)"
                    ),
                ),
                (
                    "achievement_rate",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1000),
                        ],
                        verbose_name="taux de réalisation (%)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("pending", "En attente"),
                            ("validated", "Validé"),
                            ("rejected", "Rejeté"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="statut",
                    ),
                ),
                (
                    "validated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="validé le"
                    ),
                ),
                (
                    "source",
                    models.CharField(blank=True, max_length=255, verbose_name="source"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="modifié le"),
                ),
                (
                    "commune",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indicator_values",
                        to="fati_geography.commune",
                        verbose_name="commune",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_indicator_values",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="créé par",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indicator_values",
                        to="fati_geography.department",
                        verbose_name="département",
                    ),
                ),
                (
                    "indicator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="fati_indicators.indicator",
                        verbose_name="indicateur",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indicator_values",
                        to="fati_geography.region",
                        verbose_name="région",
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="validated_indicators",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="validé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "valeur d'indicateur",
                "verbose_name_plural": "valeurs d'indicateurs",
                "ordering": ["-year", "indicator__sector", "indicator__name"],
                "unique_together": {
                    ("indicator", "region", "department", "commune", "year", "period")
                },
            },
        ),
        migrations.CreateModel(
            name="IndicatorHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_value",
                    models.FloatField(
                        blank=True, null=True, verbose_name="ancienne valeur"
                    ),
                ),
                ("new_value", models.FloatField(verbose_name="nouvelle valeur")),
                (
                    "change_reason",
                    models.TextField(
                        blank=True, verbose_name="raison de la modification"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="modifié par",
                    ),
                ),
                (
                    "indicator_value",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="fati_indicators.indicatorvalue",
                        verbose_name="valeur d'indicateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "historique d'indicateur",
                "verbose_name_plural": "historiques d'indicateurs",
                "ordering": ["-created_at"],
            },
        ),
    ]
