# Generated by Django 4.2.27 on 2026-01-31 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="nom")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("institution", "Institution"),
                            ("health", "Santé"),
                            ("education", "Éducation"),
                            ("admin", "Administration"),
                            ("contributor", "Contributeur"),
                        ],
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                (
                    "layout_config",
                    models.JSONField(
                        default=dict,
                        help_text="Configuration des widgets et leur position",
                        verbose_name="configuration de la mise en page",
                    ),
                ),
                (
                    "default_filters",
                    models.JSONField(
                        default=dict,
                        help_text="Filtres appliqués par défaut",
                        verbose_name="filtres par défaut",
                    ),
                ),
                (
                    "is_shared",
                    models.BooleanField(default=False, verbose_name="partagé"),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="par défaut"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="actif")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="modifié le"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboards",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="propriétaire",
                    ),
                ),
                (
                    "shared_with",
                    models.ManyToManyField(
                        blank=True,
                        related_name="shared_dashboards",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="partagé avec",
                    ),
                ),
            ],
            options={
                "verbose_name": "tableau de bord",
                "verbose_name_plural": "tableaux de bord",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="nom")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "sector",
                    models.CharField(
                        choices=[
                            ("health", "Santé"),
                            ("education", "Éducation"),
                            ("both", "Les deux"),
                        ],
                        default="both",
                        max_length=20,
                        verbose_name="secteur",
                    ),
                ),
                (
                    "template_config",
                    models.JSONField(
                        default=dict,
                        help_text="Sections et contenu du rapport",
                        verbose_name="configuration du modèle",
                    ),
                ),
                (
                    "available_formats",
                    models.JSONField(
                        default=list,
                        help_text="Liste des formats de sortie",
                        verbose_name="formats disponibles",
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        default=list,
                        help_text="Paramètres requis pour générer le rapport",
                        verbose_name="paramètres",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="actif")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="modifié le"),
                ),
            ],
            options={
                "verbose_name": "modèle de rapport",
                "verbose_name_plural": "modèles de rapports",
            },
        ),
        migrations.CreateModel(
            name="Widget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="nom")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("kpi", "KPI"),
                            ("kpi_list", "Liste de KPIs"),
                            ("line_chart", "Graphique linéaire"),
                            ("bar_chart", "Graphique à barres"),
                            ("pie_chart", "Graphique circulaire"),
                            ("area_chart", "Graphique en aires"),
                            ("map", "Carte"),
                            ("map_heatmap", "Carte de chaleur"),
                            ("data_table", "Tableau de données"),
                            ("facility_list", "Liste de structures"),
                            ("alert_list", "Liste d'alertes"),
                            ("alert_summary", "Résumé des alertes"),
                            ("text", "Texte"),
                            ("image", "Image"),
                            ("iframe", "IFrame"),
                        ],
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                (
                    "position_x",
                    models.PositiveIntegerField(default=0, verbose_name="position X"),
                ),
                (
                    "position_y",
                    models.PositiveIntegerField(default=0, verbose_name="position Y"),
                ),
                (
                    "width",
                    models.PositiveIntegerField(default=4, verbose_name="largeur"),
                ),
                (
                    "height",
                    models.PositiveIntegerField(default=4, verbose_name="hauteur"),
                ),
                (
                    "config",
                    models.JSONField(
                        default=dict,
                        help_text="Configuration spécifique au type de widget",
                        verbose_name="configuration",
                    ),
                ),
                (
                    "data_source",
                    models.CharField(
                        blank=True,
                        help_text="Identifiant de la source de données",
                        max_length=100,
                        verbose_name="source de données",
                    ),
                ),
                (
                    "filters",
                    models.JSONField(blank=True, default=dict, verbose_name="filtres"),
                ),
                (
                    "refresh_interval",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="intervalle de rafraîchissement (secondes)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="actif")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="modifié le"),
                ),
                (
                    "dashboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="widgets",
                        to="fati_dashboards.dashboard",
                        verbose_name="tableau de bord",
                    ),
                ),
            ],
            options={
                "verbose_name": "widget",
                "verbose_name_plural": "widgets",
                "ordering": ["position_y", "position_x"],
            },
        ),
        migrations.CreateModel(
            name="GeneratedReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="nom")),
                (
                    "parameters",
                    models.JSONField(default=dict, verbose_name="paramètres"),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="reports/%Y/%m/",
                        verbose_name="fichier",
                    ),
                ),
                ("format", models.CharField(max_length=10, verbose_name="format")),
                (
                    "generated_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="généré le"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("generating", "En cours"),
                            ("completed", "Terminé"),
                            ("failed", "Échec"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="statut",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="message d'erreur"),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="généré par",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_reports",
                        to="fati_dashboards.reporttemplate",
                        verbose_name="modèle",
                    ),
                ),
            ],
            options={
                "verbose_name": "rapport généré",
                "verbose_name_plural": "rapports générés",
                "ordering": ["-generated_at"],
            },
        ),
    ]
