# Generated by Django 4.2.27 on 2026-02-08 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fati_dashboards", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dashboard",
            name="type",
            field=models.CharField(
                choices=[
                    ("institution", "Institution"),
                    ("health", "Santé"),
                    ("education", "Éducation"),
                    ("admin", "Administration"),
                ],
                max_length=20,
                verbose_name="type",
            ),
        ),
    ]
