# Generated by Django 4.2.27 on 2026-01-31 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("fati_geography", "0001_initial"),
        ("fati_indicators", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="nom")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("indicator_value", "Valeur d'indicateur"),
                            ("facility", "Structure"),
                            ("report", "Rapport"),
                            ("data_submission", "Soumission de données"),
                        ],
                        max_length=30,
                        verbose_name="type d'entité",
                    ),
                ),
                (
                    "steps_config",
                    models.JSONField(
                        default=list,
                        help_text="Liste ordonnée des étapes avec rôle assigné",
                        verbose_name="configuration des étapes",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="actif")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="modifié le"),
                ),
            ],
            options={
                "verbose_name": "définition de workflow",
                "verbose_name_plural": "définitions de workflows",
            },
        ),
        migrations.CreateModel(
            name="WorkflowInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(max_length=50, verbose_name="type d'entité"),
                ),
                (
                    "entity_id",
                    models.CharField(max_length=100, verbose_name="ID de l'entité"),
                ),
                (
                    "current_status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("submitted", "Soumis"),
                            ("under_review", "En révision"),
                            ("validated", "Validé"),
                            ("rejected", "Rejeté"),
                            ("published", "Publié"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="statut actuel",
                    ),
                ),
                (
                    "current_step",
                    models.PositiveIntegerField(
                        default=0, verbose_name="étape actuelle"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="modifié le"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="terminé le"
                    ),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="initiated_workflows",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="initié par",
                    ),
                ),
                (
                    "workflow_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instances",
                        to="fati_workflows.workflowdefinition",
                        verbose_name="définition de workflow",
                    ),
                ),
            ],
            options={
                "verbose_name": "instance de workflow",
                "verbose_name_plural": "instances de workflows",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="nom")),
                ("order", models.PositiveIntegerField(verbose_name="ordre")),
                (
                    "assigned_role",
                    models.CharField(max_length=50, verbose_name="rôle assigné"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("in_progress", "En cours"),
                            ("completed", "Terminée"),
                            ("skipped", "Ignorée"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="statut",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="terminé le"
                    ),
                ),
                ("comments", models.TextField(blank=True, verbose_name="commentaires")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="completed_workflow_steps",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="terminé par",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="fati_workflows.workflowinstance",
                        verbose_name="workflow",
                    ),
                ),
            ],
            options={
                "verbose_name": "étape de workflow",
                "verbose_name_plural": "étapes de workflows",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("threshold", "Seuil dépassé"),
                            ("trend", "Tendance"),
                            ("anomaly", "Anomalie"),
                            ("delay", "Retard"),
                            ("validation", "Validation"),
                        ],
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critique"),
                            ("high", "Élevée"),
                            ("medium", "Moyenne"),
                            ("low", "Faible"),
                            ("info", "Info"),
                        ],
                        max_length=20,
                        verbose_name="gravité",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="titre")),
                ("message", models.TextField(verbose_name="message")),
                (
                    "sector",
                    models.CharField(
                        blank=True,
                        choices=[("health", "Santé"), ("education", "Éducation")],
                        max_length=20,
                        verbose_name="secteur",
                    ),
                ),
                (
                    "value",
                    models.FloatField(blank=True, null=True, verbose_name="valeur"),
                ),
                (
                    "threshold",
                    models.FloatField(blank=True, null=True, verbose_name="seuil"),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="lu")),
                (
                    "read_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="lu le"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "indicator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="fati_indicators.indicator",
                        verbose_name="indicateur",
                    ),
                ),
                (
                    "read_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="read_alerts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="lu par",
                    ),
                ),
                (
                    "recipients",
                    models.ManyToManyField(
                        related_name="alerts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="destinataires",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="fati_geography.region",
                        verbose_name="région",
                    ),
                ),
            ],
            options={
                "verbose_name": "alerte",
                "verbose_name_plural": "alertes",
                "ordering": ["-created_at"],
            },
        ),
    ]
