# Generated by Django 4.2.27 on 2026-01-31 14:07

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=10, unique=True, verbose_name="code"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="nom")),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326, verbose_name="géométrie"
                    ),
                ),
                (
                    "centroid",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326, verbose_name="centroïde"
                    ),
                ),
                (
                    "population",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="population"
                    ),
                ),
                (
                    "area_km2",
                    models.FloatField(
                        blank=True, null=True, verbose_name="superficie (km²)"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="métadonnées"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="modifié le"),
                ),
            ],
            options={
                "verbose_name": "région",
                "verbose_name_plural": "régions",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=10, unique=True, verbose_name="code"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="nom")),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326, verbose_name="géométrie"
                    ),
                ),
                (
                    "centroid",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326, verbose_name="centroïde"
                    ),
                ),
                (
                    "population",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="population"
                    ),
                ),
                (
                    "area_km2",
                    models.FloatField(
                        blank=True, null=True, verbose_name="superficie (km²)"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="métadonnées"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="modifié le"),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departments",
                        to="fati_geography.region",
                        verbose_name="région",
                    ),
                ),
            ],
            options={
                "verbose_name": "département",
                "verbose_name_plural": "départements",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Commune",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=10, unique=True, verbose_name="code"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="nom")),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326, verbose_name="géométrie"
                    ),
                ),
                (
                    "centroid",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326, verbose_name="centroïde"
                    ),
                ),
                (
                    "population",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="population"
                    ),
                ),
                (
                    "area_km2",
                    models.FloatField(
                        blank=True, null=True, verbose_name="superficie (km²)"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="métadonnées"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="modifié le"),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="communes",
                        to="fati_geography.department",
                        verbose_name="département",
                    ),
                ),
            ],
            options={
                "verbose_name": "commune",
                "verbose_name_plural": "communes",
                "ordering": ["name"],
            },
        ),
    ]
