# Generated by Django 4.2.27 on 2026-02-08 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fati_geography", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commune",
            name="code",
            field=models.CharField(max_length=50, unique=True, verbose_name="code"),
        ),
        migrations.AlterField(
            model_name="department",
            name="code",
            field=models.CharField(max_length=50, unique=True, verbose_name="code"),
        ),
        migrations.AlterField(
            model_name="region",
            name="code",
            field=models.CharField(max_length=50, unique=True, verbose_name="code"),
        ),
    ]
