# Generated by Django 4.2.27 on 2026-01-31 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("fati_geography", "0001_initial"),
        ("fati_indicators", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="nom")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "sector",
                    models.CharField(
                        choices=[
                            ("health", "Santé"),
                            ("education", "Éducation"),
                            ("both", "Les deux"),
                        ],
                        max_length=20,
                        verbose_name="secteur",
                    ),
                ),
                ("year", models.PositiveIntegerField(verbose_name="année")),
                (
                    "period",
                    models.CharField(blank=True, max_length=50, verbose_name="période"),
                ),
                ("start_date", models.DateField(verbose_name="date de début")),
                ("end_date", models.DateField(verbose_name="date de fin")),
                (
                    "geographic_scope",
                    models.CharField(
                        choices=[
                            ("national", "National"),
                            ("regional", "Régional"),
                            ("department", "Départemental"),
                            ("commune", "Communal"),
                        ],
                        max_length=20,
                        verbose_name="portée géographique",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planifiée"),
                            ("ongoing", "En cours"),
                            ("completed", "Terminée"),
                            ("closed", "Clôturée"),
                        ],
                        default="planned",
                        max_length=20,
                        verbose_name="statut",
                    ),
                ),
                (
                    "response_rate",
                    models.FloatField(
                        default=0,
                        help_text="Pourcentage de territoires ayant soumis des données",
                        verbose_name="taux de réponse (%)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="modifié le"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_collections",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="créé par",
                    ),
                ),
                (
                    "indicators",
                    models.ManyToManyField(
                        related_name="data_collections",
                        to="fati_indicators.indicator",
                        verbose_name="indicateurs",
                    ),
                ),
                (
                    "regions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="data_collections",
                        to="fati_geography.region",
                        verbose_name="régions",
                    ),
                ),
            ],
            options={
                "verbose_name": "collecte de données",
                "verbose_name_plural": "collectes de données",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="FormTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="nom")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "sector",
                    models.CharField(
                        choices=[("health", "Santé"), ("education", "Éducation")],
                        max_length=20,
                        verbose_name="secteur",
                    ),
                ),
                ("schema", models.JSONField(default=dict, verbose_name="schéma")),
                (
                    "ui_schema",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="schéma UI"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="actif")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="modifié le"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_forms",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="créé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "modèle de formulaire",
                "verbose_name_plural": "modèles de formulaires",
            },
        ),
        migrations.CreateModel(
            name="DataSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("submitted", "Soumis"),
                            ("under_review", "En révision"),
                            ("validated", "Validé"),
                            ("rejected", "Rejeté"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="statut",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="soumis le"
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="révisé le"
                    ),
                ),
                (
                    "reviewer_notes",
                    models.TextField(blank=True, verbose_name="notes du réviseur"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="modifié le"),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="fati_data_collection.datacollection",
                        verbose_name="collecte",
                    ),
                ),
                (
                    "commune",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_submissions",
                        to="fati_geography.commune",
                        verbose_name="commune",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_submissions",
                        to="fati_geography.department",
                        verbose_name="département",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_submissions",
                        to="fati_geography.region",
                        verbose_name="région",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_submissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="révisé par",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_submissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="soumis par",
                    ),
                ),
            ],
            options={
                "verbose_name": "soumission de données",
                "verbose_name_plural": "soumissions de données",
                "unique_together": {("collection", "region", "department", "commune")},
            },
        ),
        migrations.CreateModel(
            name="DataEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.FloatField(verbose_name="valeur")),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "attachments",
                    models.JSONField(
                        blank=True, default=list, verbose_name="pièces jointes"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="modifié le"),
                ),
                (
                    "indicator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_entries",
                        to="fati_indicators.indicator",
                        verbose_name="indicateur",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="fati_data_collection.datasubmission",
                        verbose_name="soumission",
                    ),
                ),
            ],
            options={
                "verbose_name": "entrée de données",
                "verbose_name_plural": "entrées de données",
                "unique_together": {("submission", "indicator")},
            },
        ),
    ]
