# Generated by Django 4.2.27 on 2026-02-08 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fati_data_collection", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="datacollection",
            options={
                "ordering": ["-start_date"],
                "verbose_name": "cycle de collecte",
                "verbose_name_plural": "cycles de collecte",
            },
        ),
    ]
