# Generated by Django 4.2.27 on 2026-02-09 00:01

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fati_data_collection", "0002_alter_datacollection_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasubmission",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                help_text="Position géographique au moment de la saisie",
                null=True,
                srid=4326,
                verbose_name="localisation GPS",
            ),
        ),
    ]
