# Generated by Django 4.2.27 on 2026-01-31 14:07

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fati_geography", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EducationFacility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="code"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="nom")),
                (
                    "facility_type",
                    models.CharField(
                        choices=[
                            ("preschool", "Préscolaire"),
                            ("primary", "Primaire"),
                            ("secondary", "Collège"),
                            ("high_school", "Lycée"),
                            ("university", "Université"),
                            ("vocational", "Formation professionnelle"),
                        ],
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("basic", "De base"),
                            ("secondary", "Secondaire"),
                            ("superior", "Supérieur"),
                        ],
                        max_length=20,
                        verbose_name="niveau",
                    ),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326, verbose_name="localisation"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="adresse")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="téléphone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email"),
                ),
                (
                    "principal_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="directeur"
                    ),
                ),
                (
                    "student_capacity",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="capacité d'accueil"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="actif")),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="métadonnées"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="modifié le"),
                ),
                (
                    "commune",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="education_facilities",
                        to="fati_geography.commune",
                        verbose_name="commune",
                    ),
                ),
            ],
            options={
                "verbose_name": "établissement d'enseignement",
                "verbose_name_plural": "établissements d'enseignement",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="HealthFacility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="code"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="nom")),
                (
                    "facility_type",
                    models.CharField(
                        choices=[
                            ("hospital", "Hôpital"),
                            ("health_center", "Centre de santé"),
                            ("health_post", "Poste de santé"),
                            ("clinic", "Clinique"),
                            ("other", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("reference", "Hôpital de référence"),
                            ("district", "Hôpital de district"),
                            ("regional", "Hôpital régional"),
                            ("university", "CHU"),
                        ],
                        max_length=20,
                        verbose_name="catégorie",
                    ),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326, verbose_name="localisation"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="adresse")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="téléphone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email"),
                ),
                (
                    "manager_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="responsable"
                    ),
                ),
                (
                    "bed_capacity",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="capacité en lits"
                    ),
                ),
                (
                    "services",
                    models.JSONField(blank=True, default=list, verbose_name="services"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="actif")),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="métadonnées"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="modifié le"),
                ),
                (
                    "commune",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_facilities",
                        to="fati_geography.commune",
                        verbose_name="commune",
                    ),
                ),
            ],
            options={
                "verbose_name": "structure de santé",
                "verbose_name_plural": "structures de santé",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("doctor", "Médecin"),
                            ("nurse", "Infirmier"),
                            ("midwife", "Sage-femme"),
                            ("technician", "Technicien"),
                            ("admin", "Personnel administratif"),
                            ("other", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="catégorie",
                    ),
                ),
                ("total", models.PositiveIntegerField(default=0, verbose_name="total")),
                (
                    "filled",
                    models.PositiveIntegerField(default=0, verbose_name="pourvu"),
                ),
                (
                    "vacant",
                    models.PositiveIntegerField(default=0, verbose_name="vacant"),
                ),
                (
                    "last_updated",
                    models.DateField(
                        auto_now=True, verbose_name="dernière mise à jour"
                    ),
                ),
                (
                    "education_facility",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff",
                        to="fati_facilities.educationfacility",
                        verbose_name="établissement d'enseignement",
                    ),
                ),
                (
                    "health_facility",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff",
                        to="fati_facilities.healthfacility",
                        verbose_name="structure de santé",
                    ),
                ),
            ],
            options={
                "verbose_name": "personnel",
                "verbose_name_plural": "personnels",
            },
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="nom")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("imaging", "Imagerie médicale"),
                            ("laboratory", "Laboratoire"),
                            ("surgery", "Chirurgie"),
                            ("emergency", "Urgence"),
                            ("other", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="catégorie",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=0, verbose_name="quantité"),
                ),
                (
                    "functional",
                    models.PositiveIntegerField(default=0, verbose_name="fonctionnel"),
                ),
                (
                    "non_functional",
                    models.PositiveIntegerField(
                        default=0, verbose_name="non fonctionnel"
                    ),
                ),
                (
                    "last_updated",
                    models.DateField(
                        auto_now=True, verbose_name="dernière mise à jour"
                    ),
                ),
                (
                    "health_facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment",
                        to="fati_facilities.healthfacility",
                        verbose_name="structure de santé",
                    ),
                ),
            ],
            options={
                "verbose_name": "équipement",
                "verbose_name_plural": "équipements",
            },
        ),
    ]
